# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  DOCKER_BUILDKIT: 1

stages:
- stage: Release
  displayName: Release
  pool:
    vmImage: 'ubuntu-latest'
  jobs:  
  - job: Build_Identity
    displayName: Build Identity
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: 'Write-Host $env:Build_SourceBranch'
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub Magic Media'
        repository: 'magicmedia/magic-media-identity'
        command: 'buildAndPush'
        Dockerfile: './.docker/identity.Dockerfile'
        buildContext: .
        addPipelineData: false
        tags:  |
          $(Build.BuildId)
          latest