# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Release
  displayName: Release
  pool:
    vmImage: 'ubuntu-latest'
  jobs:  
  - job: Build_Host
    displayName: Build Host
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: 'yarn --cwd ./src/UI/media-ui'
