#import "../ImageBoxFragment.gql"

query mediaInfo($id: UUID!) {
  mediaById(id: $id) {
    id
    filename
    dateTaken
    cameraId
    size
    isFavorite
    mediaType
    folder
    source {
      identifier
      importedAt
      type
    }
    videoInfo {
      duration
      bitrate
      format
      frameRate
    }
    dimension {
      height
      width
    }
    camera {
      id
      model
      make
    }
    geoLocation {
      point {
        coordinates
      }
      altitude
      address {
        name
        address
        city
        country
        distric1
        distric2
        countryCode
      }
    }
    faces {
      id
      mediaId
      box {
        ...bbox
      }
      thumbnail {
        id
      }
      person {
        id
        name
        dateOfBirth
      }
      personId
      recognitionType
      age
      state
    }
    files {
      filename
      location
      type
      size
    }
    ai(minConfidence: 10) {
      objects {
        name
        confidence
        source
        box {
          ...bbox
        }
      }
      tags {
        name
        confidence
        source
      }
      caption {
        text
        confidence
      }
      colors {
        accent
        dominantBackground
        dominantForeground
        isBackWhite
      }
    }
  }
}