#import "../ImageBoxFragment.gql"

query mediaDetails($id: UUID!) {
  mediaById(id: $id) {
    id
    filename
    dateTaken
    cameraId
    size
    isFavorite
    mediaType
    folder
    videoInfo {
      duration
    }
    dimension {
      height
      width
    }
    camera {
      id
      model
      make
    }
    geoLocation {
      point {
        coordinates
      }
      altitude
      address {
        name
        address
        city
        country
        countryCode
      }
    }
    tags {
      definition {
        id
        name
        color
      }
      data
    }
    faces {
      id
      mediaId
      box {
        ...bbox
      }
      thumbnail {
        id
      }
      person {
        id
        name
        dateOfBirth
      }
      personId
      recognitionType
      age
      state
    }
    thumbnail(size: M) {
      size
      dataUrl
      dimensions {
        height
        width
      }
    }
    ai(minConfidence: 30) {
      objects {
        name
        confidence
        source
        box {
          ...bbox
        }
      }
      caption {
        text
        confidence
      }
      colors {
        accent
      }
    }
  }
}
