query search(
  $request: SearchMediaRequestInput!
  $size: ThumbnailSizeName
  $loadThumbnailData: Boolean!
) {
  searchMedia(request: $request) {
    items {
      id
      filename
      dateTaken
      cameraId
      isFavorite
      mediaType
      videoInfo {
        duration
      }
      camera {
        id
        model
        make
      }
      dimension {
        height
        width
      }
      thumbnail(size: $size, loadData: $loadThumbnailData) {
        size
        dataUrl
        dimensions {
          height
          width
        }
      }
      source {
        identifier
        type
      }
    }
    hasMore
  }
}
