query getAlbumById($id: Uuid!) {
  album(id: $id) {
    id
    title
    videoCount
    imageCount
    folders
    thumbnail {
      dataUrl
    }
    startDate
    endDate
    folders
    filters{
      key
      name
      value
      description
    }
    allMediaIds
    persons {
      personId
      faceId
      name
      count
    }
    countries {
      name
      code
      count
      cities {
        name
        count
      }
    }
  }
}
