#import "../UserErrorFragment.gql"

mutation removeFoldersFromAlbum($input: RemoveFoldersFromAlbumInput!) {
  removeFoldersFromAlbum(input: $input) {
    album {
      id
      title
    }
    errors {
      ...userError
    }
  }
}
