query searchAlbums($input: SearchAlbumRequestInput!) {
  searchAlbums(input: $input) {
    items {
      id
      title
      videoCount
      imageCount
      thumbnail {
        dataUrl
      }
      startDate
      endDate
      countries {
        name
        code
      }
    }
  }
}