query getUserById($id: UUID!) {
  user(id: $id) {
    id
    email
    name
    state
    invitationCode
    person {
      id
      name
    }
    sharedAlbums {
      id
      title
    }
    inAlbum{
      id
      title
    }
    authorizedOnMediaCount
  }
}
