query searchUsers($input: SearchUserInput!) {
  searchUsers(input: $input) {
    items {
      id
      name
      email
      roles
      state
      person{
        id
        thumbnail{
          dataUrl
        }

      }
    }
    totalCount
    hasMore
  }
}
