query searchPersons($input: SearchPersonRequestInput!) {
 searchPersons(input: $input) {
    items {
      id
      name
      dateOfBirth
      groups{
        id
        name
      }
      thumbnail{
        dataUrl
      }
      summary{
        computerCount,
        mediaCount
        humanCount
        validatedCount
      }
    },
    totalCount
    hasMore
  }
}
