query searchAuditEvents($request: SearchAuditInput!) {
  searchAuditEvents(request: $request) {
    items {
      timestamp
      user{
        id
        name
      }
      action
      media{
        folder
        dateTaken
      }
      thumbprint{
        ipInfo
        {
          ipAddress
          country,
          countryCode
          city
        }
        userAgent{
          description
        }
      }
      success

      resource {
        id
        type
      }
      thumbnail
    }
    totalCount
  }
}
