FROM hellozcb/face_recognition

RUN pip install --upgrade pip && \
  pip install imutils && \
  pip install opencv-python && \
  pip install --upgrade ptvsd && \
  pip install sklearn && \
  pip install Flask && \
  pip install isodate && \
  pip3 install tensorflow==1.15  && \
  pip3 install python-graphql-client && \
  pip3 install pillow && \
  pip3 install matplotlib && \
  pip3 install h5py && \
  pip3 install keras==2.2.4

RUN rm -f /app/models/shape_predictor_5_face_landmarks.dat.bz && \
  rm -f /app/models/shape_predictor_68_face_landmarks.dat.bz2

ADD https://github.com/davisking/dlib-models/raw/master/shape_predictor_5_face_landmarks.dat.bz2 /app/models/
ADD https://github.com/davisking/dlib-models/raw/master/shape_predictor_68_face_landmarks.dat.bz2 /app/models/

RUN bzip2 -d /app/models/shape_predictor_5_face_landmarks.dat.bz2 && \
  bzip2 -d /app/models/shape_predictor_68_face_landmarks.dat.bz2
