#import "../UserErrorFragment.gql"
#import "./FaceFragment.gql"

mutation approveAllFacesByMedia($mediaId: UUID!) {
  approveAllFacesByMedia(mediaId: $mediaId) {
    faces {
      ...face
    }
    errors {
      ... userError
    }
  }
}
