#import "../UserErrorFragment.gql"

mutation assignPersonByHuman($input: AssignPersonByHumanInput!) {
  assignPersonByHuman(input: $input) {
    face {
      id
      mediaId
      recognitionType
      state
      age
      box {
        left
        top
        right
        bottom
      }
      person {
        id
        name
        dateOfBirth
      }
      thumbnail {
        id
      }
    }
    errors {
      ...userError
    }
  }
}
