#import "./FaceFragment.gql"
#import "../UserErrorFragment.gql"

mutation predictPerson($input: PredictPersonInput!) {
  predictPerson(input: $input) {
    hasMatch
    face {
      ...face
    }
    errors {
      ...userError
    }
  }
}
