#import "../UserErrorFragment.gql"
#import "./FaceFragment.gql"

mutation unAssignAllPredictedByMedia($mediaId: Uuid!) {
  unAssignAllPredictedPersonsByMedia(mediaId: $mediaId) {
    faces {
      ...face
    }
    errors {
      ...userError
    }
  }
}
