#import "./FaceFragment.gql"
#import "../UserErrorFragment.gql"

mutation unassignPersonFromFace($id: Uuid!) {
  unAssignPersonFromFace(id: $id) {
    face {
      ...face
    }
    errors {
      ...userError
    }
  }
}
