fragment face on MediaFace {
      id
      mediaId
      box {
        left
        top
        right
        bottom
      }
      recognitionType
      state
      age
      personId
      person {
        id
        name
        dateOfBirth
      },
        thumbnail {
        id
      }
}