query mediaDetails($id: Uuid!) {
  mediaById(id: $id) {
    id
    filename
    dateTaken
    cameraId
    dimension {
      height
      width
    }
    camera {
      id
      model
      make
    }
    thumbnail(size: M) {
      size
      dataUrl
      dimensions {
        height
        width
      }
    }
  }
}
