query mediaDetails($id: Uuid!) {
  mediaById(id: $id) {
    id
    filename
    dateTaken
    cameraId
    isFavorite
    mediaType
    folder
    videoInfo{
      duration
    }
    dimension {
      height
      width
    }
    camera {
      id
      model
      make
    }
    geoLocation{
      address{
        name
        address
        city
        country
        countryCode
      }
    }
    faces {
      id
      box {
        left
        top
        right
        bottom
      }
      thumbnail {
        id
      }
      person {
        id
        name
        dateOfBirth
      }
      personId
      recognitionType
      age
      state
    }
    thumbnail(size: M) {
      size
      dataUrl
      dimensions {
        height
        width
      }
    }
  }
}