query mediaDetails($id: Uuid!) {
  mediaById(id: $id) {
    id
    filename
    dateTaken
    cameraId
    dimension {
      height
      width
    }
    camera {
      id
      model
      make
    }
    faces {
      id
      box {
        left
        top
        right
        bottom
      }
      thumbnail {
        id
      }
      person {
        id
        name
        dateOfBirth
        group
      }
      personId
    }
    thumbnail(size: M) {
      size
      dataUrl
      dimensions {
        height
        width
      }
    }
  }
}