#import "./FaceFragment.gql"
#import "./UserErrorFragment.gql"

mutation predictPerson($input: PredictPersonInput!) {
  predictPerson(input: $input) {
    face {
      ...face
    }
    errors {
      ...userError
    }
  }
}