query searchFaces($request: SearchFacesRequestInput!) {
  searchFaces(request: $request) {
    items {
      id
      media {
        id
        filename
      }
      person {
        id
        name
      }
      recognitionType
      state
      distanceThreshold
      age
      thumbnail {
        id
        dataUrl
        dimensions {
          height
          width
        }
      }
    }
    totalCount
  }
}
