query search($request: SearchMediaRequestInput!, $size: ThumbnailSizeName) {
  searchMedia(request: $request) {
    items {
      id
      filename
      dateTaken
      cameraId
      isFavorite
      camera {
        id
        model
        make
      }
      dimension {
        height
        width
      }
      thumbnail(size: $size) {
        size
        dataUrl
        dimensions {
          height
          width
        }
      }
      source {
        identifier
        type
      }
    }
    totalCount
  }
}
