query search($request: SearchMediaRequestInput! ) {
  searchMedia(request: $request) {
    id
    filename
    dateTaken
    cameraId
    camera {
      id
      model
      make
    }
    dimension {
      height
       width
    }
    thumbnail(size: L) {
      size
      dataUrl
      dimensions {
        height
        width
      }
    }
    source {
      identifier
      type
    }
  }
}
