query facets {
  facets {
    country {
      ...facet
    }
    city {
      ...facet
    },
    camera {
      ...facet
    },
    aiTags{
      ... facet
    },
    aiObjects{
      ... facet
    }
  }
}

fragment facet on SearchFacetItem {
  text
  value
  count
}
